language: java
jdk:
  - openjdk11

jobs:
  include:
    - stage: publish
      script:
        - openssl aes-256-cbc -K $encrypted_3d03fa02db61_key -iv $encrypted_3d03fa02db61_iv -in gpg.asc.enc -out gpg.asc -d
        - gpg --import gpg.asc
        - mvn -s .travis-mvn.xml deploy -DskipTests -Dflatten -Dsign -Dgpg.passphrase=$GPG_PASSPHRASE

stages:
  - compile
  - test
  - name: publish
    if: branch = master OR tag IS present
