language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: publish
      script: mvn -f libpuzzle -s .travis-mvn.xml deploy -DskipTests

stages:
  - compile
  - test
  - name: publish
    if: branch = master