language: java
jdk:
  - openjdk11

jobs:
  include:
    - stage: publish
      script: mvn -s .travis-mvn.xml deploy -DskipTests -Dflatten

stages:
  - compile
  - test
  - name: publish
    if: branch = master OR tag IS present
